import { useState, type FormEvent } from "react";
import { useAppContext } from "./context/AppContext";

const mapUrl = "https://maps.app.goo.gl/2kppx7BY9YVrrv3p9?g_st=ic";
const weddingAsset = (filename: string) => `${import.meta.env.BASE_URL}wedding/${filename}`;

const content = {
  en: {
    nav: ["Details", "Our story", "Dress code", "RSVP"], weddingOf: "The wedding of", date: "June 11, 2027", lake: "White Meadow Lake, NJ",
    celebration: "A lakeside celebration", invitationEyebrow: "The wedding of", invitationMood: "Romantic · Timeless · Lakeside", detailsTitle: <>A day made for<br /><em>the people we love.</em></>, detailsText: "Join us for a warm and timeless evening by the water as we celebrate the beginning of our next chapter.", when: "When", where: "Where", friday: "Friday, June 11", time: "2027 · 5:00 PM", venue: "White Meadow Lake", venueDetail: "Country Club · Rockaway, NJ", maps: "Open in maps",
    storyLabel: "Our story", storyTitle: <>It started with<br /><em>a quiet prayer.</em></>, storyQuote: "“This story starts way before their first exchange of words.”", story: ["Freshman year, the first time Isaiah saw Hillary, he thought: “wow, she is beautiful.” Not quite ready to say hello, he made a prayer: if it was meant to be, they would cross paths in high school.", "Nearly four years later, with a little help from their friends Nico and his then-girlfriend, they finally met. At first it was only “hi” and “bye,” but there was a spark eager to be fed.", "Then came prom. Between flirting and small talk, Isaiah found the confidence to send Hillary a late-night DM asking for photos from the night. They texted for hours, then days, weeks, and months—until he finally asked her to be his girlfriend."],
    dressLabel: "Dress code", dressTitle: <>Lakeside<br /><em>elegance.</em></>, dressLead: "We invite our guests to dress in warm, earthy tones inspired by the natural beauty of the lake.", dressText: "Please join us in elevated neutrals and rich earth tones: beige, tan, taupe, caramel, mocha, and chocolate. We kindly ask guests to avoid white, ivory, blue, and green.",
    giftLabel: "With love", giftTitle: <>Your presence is<br /><em>the greatest gift.</em></>, giftText: "Your presence at our celebration is truly enough. For those who wish to honor us with a gift, a contribution toward our future together would be received with heartfelt gratitude.", zelleLabel: "Zelle", zelleEmail: "Guzman.wedding27@gmail.com",
    rsvpLabel: "RSVP", rsvpTitle: <>We can’t wait to<br /><em>celebrate with you.</em></>, rsvpIntro: "Please reply by", deadline: "May 1, 2027", name: "Full name", email: "Email address", attendance: "Will you be joining us?", yes: "Joyfully accepts", guests: "Your reserved seats", allSeats: "We are delighted to accept all reserved seats", fewerSeats: "We are pleased to attend, but will use fewer seats (please note the final count below)", no: "Regretfully declines", message: "Final guest count or a note for the couple (optional)", submit: "Send RSVP", sending: "Sending…", thankYou: "Thank you for your response.", thankYouText: "We’re so happy to celebrate this season with you.", retry: "We couldn’t send your response. Please try again.", language: "ES", scroll: "Discover the details", project: "Your own website", guestCount: "Final guest count", back: "Back to top"
  },
  es: {
    nav: ["Detalles", "Nuestra historia", "Código de vestimenta", "RSVP"], weddingOf: "La boda de", date: "11 de junio de 2027", lake: "White Meadow Lake, NJ",
    celebration: "Una celebración junto al lago", invitationEyebrow: "La boda de", invitationMood: "Romántica · Atemporal · Junto al lago", detailsTitle: <>Un día creado para<br /><em>las personas que amamos.</em></>, detailsText: "Acompáñanos a una velada cálida y atemporal junto al lago mientras celebramos el comienzo de nuestro próximo capítulo.", when: "Cuándo", where: "Dónde", friday: "Viernes, 11 de junio", time: "2027 · 5:00 PM", venue: "White Meadow Lake", venueDetail: "Country Club · Rockaway, NJ", maps: "Abrir en Maps",
    storyLabel: "Nuestra historia", storyTitle: <>Todo comenzó con<br /><em>una pequeña oración.</em></>, storyQuote: "“Esta historia comenzó mucho antes de que intercambiaran sus primeras palabras.”", story: ["En primer año de secundaria, la primera vez que Isaiah vio a Hillary pensó: «wow, ella es hermosa». Sin reunir todavía el valor para hablarle, hizo una oración: si estaba destinado a ser, se encontrarían en la secundaria.", "Casi cuatro años después, con un poco de ayuda de su amigo de siempre Nico y su entonces novia, por fin se conocieron. Al principio solo era «hola» y «adiós», pero había una chispa esperando crecer.", "Luego llegó el baile de graduación. Entre coqueteos y conversaciones, Isaiah reunió el valor para enviarle a Hillary un mensaje después de medianoche preguntándole por las fotos de la noche. Hablaron por horas, después días, semanas y meses, hasta que finalmente le pidió ser su novia."],
    dressLabel: "Código de vestimenta", dressTitle: <>Elegancia<br /><em>junto al lago.</em></>, dressLead: "Invitamos a nuestros invitados a vestir tonos cálidos y tierra inspirados en la belleza natural del lago.", dressText: "Acompáñanos con neutrales elevados y tonos tierra intensos: beige, tostado, taupe, caramelo, moka y chocolate. Les pedimos amablemente evitar blanco, marfil, azul y verde.",
    giftLabel: "Con cariño", giftTitle: <>Su presencia es<br /><em>el mejor regalo.</em></>, giftText: "Su presencia en nuestra celebración es más que suficiente. Para quienes deseen honrarnos con un regalo, recibiríamos con mucho cariño una contribución para nuestro futuro juntos.", zelleLabel: "Zelle", zelleEmail: "Guzman.wedding27@gmail.com",
    rsvpLabel: "RSVP", rsvpTitle: <>Estamos deseando<br /><em>celebrar contigo.</em></>, rsvpIntro: "Por favor responde antes del", deadline: "1 de mayo de 2027", name: "Nombre completo", email: "Correo electrónico", attendance: "¿Nos acompañarás?", yes: "Aceptamos con alegría", guests: "Sus asientos reservados", allSeats: "Con mucho gusto aceptamos todos los asientos reservados", fewerSeats: "Con gusto asistiremos, pero utilizaremos menos asientos (indica el número final abajo)", no: "Lamentablemente no podremos asistir", message: "Cantidad final de invitados o un mensaje para los novios (opcional)", submit: "Enviar RSVP", sending: "Enviando…", thankYou: "Gracias por tu respuesta.", thankYouText: "Nos hace mucha ilusión celebrar esta etapa contigo.", retry: "No pudimos enviar tu respuesta. Inténtalo nuevamente.", language: "EN", scroll: "Descubre los detalles", project: "Tu propio proyecto web", guestCount: "Cantidad final de invitados", back: "Volver arriba"
  }
};

function App() {
  const { siteTitle, locale, setLocale } = useAppContext();
  const c = content[locale];
  const [submission, setSubmission] = useState<"idle" | "sending" | "success" | "error">("idle");
  const [attendance, setAttendance] = useState("");
  const [reservedSeats, setReservedSeats] = useState("");
  const scrollTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "instant" : "smooth", block: "start" });

  async function submitRsvp(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (submission === "sending") return;
    setSubmission("sending");
    const form = event.currentTarget;
    const data = new URLSearchParams();
    new FormData(form).forEach((value, key) => data.set(key, String(value)));
    const body = data.toString();
    try {
      const response = await fetch("/", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body });
      if (!response.ok) throw new Error("Submission failed");
      setSubmission("success");
      form.reset();
    } catch {
      setSubmission("error");
    }
  }

  return <main className="overflow-hidden bg-[#f7f1e7] text-[#4d443b]">
    <header className="fixed inset-x-0 top-0 z-30 border-b border-[#6c5944]/10 bg-[#f7f1e7]/90 backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 md:px-10">
      <button className="font-display text-xl tracking-[0.1em] text-[#5a4634] md:text-2xl" onClick={() => scrollTo("top")}>H <span className="text-[#bca57e]">+</span> I</button>
      <nav className="hidden items-center gap-7 text-[10px] uppercase tracking-[0.22em] text-[#6c5944]/75 md:flex"><button onClick={() => scrollTo("details")}>{c.nav[0]}</button><button onClick={() => scrollTo("story")}>{c.nav[1]}</button><button onClick={() => scrollTo("dress-code")}>{c.nav[2]}</button><button onClick={() => scrollTo("rsvp")}>{c.nav[3]}</button></nav>
      <div className="flex items-center gap-3"><button className="text-[10px] uppercase tracking-[.2em] text-[#715e49] underline-offset-4 hover:underline" onClick={() => setLocale(locale === "en" ? "es" : "en")}>{c.language}</button><button className="rounded-full border border-[#81694e] px-4 py-2 text-[10px] uppercase tracking-[0.19em] text-[#5a4634] transition hover:bg-[#5a4634] hover:text-[#f7f1e7]" onClick={() => scrollTo("rsvp")}>RSVP</button></div>
    </div></header>
    <section id="top" className="relative isolate hero-section pt-20"><img className="absolute inset-0 -z-20 h-full w-full object-cover object-center" src={weddingAsset("hero.jpg")} alt="Hillary and Isaiah sharing a moment outdoors" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(44,34,23,.78),rgba(70,54,36,.38)_54%,rgba(31,27,21,.52)),radial-gradient(circle_at_70%_20%,rgba(197,164,111,.18),transparent_38%)]" /><div className="mx-auto flex hero-content max-w-7xl items-end px-5 pb-32 md:px-10 md:pb-36"><div className="max-w-3xl text-[#fffaf1]"><p className="mb-6 text-[10px] uppercase tracking-[0.42em] text-[#f0debe]">{c.weddingOf}</p><h1 className="font-display text-6xl leading-[0.84] tracking-[-0.055em] sm:text-7xl md:text-9xl">Hillary<br /><em className="font-light">&amp;</em> Isaiah</h1><div className="mt-9 flex flex-wrap gap-x-8 gap-y-3 border-t border-white/40 pt-5 text-xs uppercase tracking-[0.2em] text-[#fff7eb]/90"><span>{c.date}</span><span>{c.lake}</span></div></div></div><a className="hero-scroll" href="#details"><span>{c.scroll}</span><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M12 3v17m-7-7 7 7 7-7" /></svg></a></section>
    <section id="details" className="scroll-mt-20 px-5 py-20 md:px-10 md:py-32"><div className="mx-auto grid max-w-6xl gap-14 md:grid-cols-[0.9fr_1.1fr] md:items-center"><div className="relative mx-auto w-full max-w-md"><div className="relative overflow-hidden bg-[#eee5d7] p-5 shadow-[12px_14px_0_rgba(205,189,159,.34)]"><p className="text-center text-[9px] uppercase tracking-[.35em] text-[#907b60]">{c.invitationEyebrow}</p><p className="mt-5 text-center font-display text-5xl leading-[.82] tracking-[-.05em] text-[#594838]">Hillary<br /><em>&amp;</em> Isaiah</p><img className="mt-8 aspect-[4/3] w-full object-cover" src={weddingAsset("lake-1.jpeg")} alt="White Meadow Lake Country Club by the lake" /><div className="absolute bottom-11 right-1 w-[44%] border-[5px] border-[#eee5d7] shadow-lg"><img className="aspect-square w-full object-cover" src={weddingAsset("lake-2.jpeg")} alt="White Meadow Lake Country Club" /></div><p className="mt-6 text-center text-[9px] uppercase tracking-[.24em] text-[#907b60]">{c.invitationMood}</p><p className="mt-2 text-center text-[10px] uppercase tracking-[.18em] text-[#66594b]">White Meadow Lake Country Club, NJ</p></div></div><div className="max-w-xl"><p className="section-label">{c.celebration}</p><h2 className="section-title mt-5">{c.detailsTitle}</h2><p className="mt-7 max-w-lg text-base leading-8 text-[#66594b]">{c.detailsText}</p><div className="mt-10 grid gap-7 border-t border-[#cdbd9f] pt-8 sm:grid-cols-2"><div><p className="detail-label">{c.when}</p><p className="mt-2 font-display text-2xl">{c.friday}</p><p className="mt-1 text-sm text-[#66594b]">{c.time}</p></div><div><p className="detail-label">{c.where}</p><p className="mt-2 font-display text-2xl">{c.venue}</p><p className="mt-1 text-sm text-[#66594b]">{c.venueDetail}</p></div></div><a className="link-arrow mt-10" href={mapUrl} target="_blank" rel="noreferrer">{c.maps} <span>↗</span></a></div></div></section>
    <section id="story" className="scroll-mt-20 bg-[#e7ddcb] px-5 py-20 md:px-10 md:py-32"><div className="mx-auto max-w-6xl"><div className="mb-14 max-w-2xl"><p className="section-label">{c.storyLabel}</p><h2 className="section-title mt-5">{c.storyTitle}</h2></div><div className="grid gap-8 md:grid-cols-[0.84fr_1.16fr] md:items-start"><img className="h-[430px] w-full object-cover md:h-[600px]" src={weddingAsset("story-1.jpg")} alt="Hillary and Isaiah together" /><div className="md:pt-12"><p className="font-display text-2xl leading-[1.35] text-[#574737] md:text-3xl">{c.storyQuote}</p><div className="mt-8 max-w-xl space-y-5 text-[15px] leading-8 text-[#66594b]">{c.story.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div></div><div className="mt-8 grid gap-8 sm:grid-cols-2"><img className="h-80 w-full object-cover" src={weddingAsset("story-2.jpg")} alt="A candid moment together" /><img className="h-80 w-full object-cover object-center" src={weddingAsset("gallery-wide.jpg")} alt="Hillary and Isaiah outdoors" /></div></div></section>
    <section id="dress-code" className="scroll-mt-20 px-5 py-20 md:px-10 md:py-32"><div className="mx-auto grid max-w-6xl gap-12 md:grid-cols-[1.1fr_0.9fr] md:items-center"><div className="order-2 md:order-1"><p className="section-label">{c.dressLabel}</p><h2 className="section-title mt-5">{c.dressTitle}</h2><p className="mt-7 max-w-md text-base leading-8 text-[#66594b]">{c.dressLead}</p><div className="mt-8 flex gap-3"><i className="h-9 w-9 rounded-full bg-[#d9c5a8]" /><i className="h-9 w-9 rounded-full bg-[#b68e5a]" /><i className="h-9 w-9 rounded-full bg-[#836044]" /><i className="h-9 w-9 rounded-full bg-[#704b37]" /><i className="h-9 w-9 rounded-full bg-[#3f281d]" /></div><p className="mt-6 max-w-md text-sm leading-7 text-[#66594b]">{c.dressText}</p></div><img className="order-1 mx-auto w-full max-w-sm border border-[#cdbd9f] p-2 md:order-2" src={weddingAsset("dress-code.png")} alt="Lakeside elegance dress code inspiration" /></div></section>
    <section className="bg-[#667e91] px-5 py-20 text-[#fff9ed] md:px-10 md:py-28"><div className="mx-auto grid max-w-6xl gap-10 md:grid-cols-[1fr_1fr] md:items-center"><div><p className="text-[10px] uppercase tracking-[0.38em] text-[#e9d6b6]">{c.giftLabel}</p><h2 className="mt-5 font-display text-5xl leading-none tracking-[-0.04em] md:text-6xl">{c.giftTitle}</h2></div><div className="md:justify-self-end"><p className="max-w-md leading-8 text-[#f5ecdf]/85">{c.giftText}</p><div className="mt-8 inline-flex flex-col border-y border-[#e9d6b6]/70 py-4"><span className="text-[10px] uppercase tracking-[.24em] text-[#e9d6b6]">{c.zelleLabel}</span><a className="mt-2 break-all font-display text-xl sm:text-2xl tracking-wide transition-opacity hover:opacity-70" href={`mailto:${c.zelleEmail}`}>{c.zelleEmail}</a></div></div></div></section>
    <section id="rsvp" className="scroll-mt-20 px-5 py-20 md:px-10 md:py-32"><div className="mx-auto max-w-3xl text-center"><p className="section-label">{c.rsvpLabel}</p><h2 className="section-title mt-5">{c.rsvpTitle}</h2><p className="mx-auto mt-7 max-w-lg leading-8 text-[#66594b]">{c.rsvpIntro} <strong className="font-semibold text-[#574737]">{c.deadline}</strong>.</p>{submission === "success" ? <div role="status" className="mt-12 border-y border-[#cdbd9f] py-10"><p className="font-display text-3xl text-[#574737]">{c.thankYou}</p><p className="mt-3 text-[#66594b]">{c.thankYouText}</p></div> : <form className="rsvp-form mt-12 text-left" name="rsvp" action="/" aria-busy={submission === "sending"} method="POST" data-netlify="true" netlify-honeypot="bot-field" onSubmit={submitRsvp}><input type="hidden" name="form-name" value="rsvp" /><p className="hidden"><label>Don’t fill this out <input name="bot-field" tabIndex={-1} autoComplete="off" /></label></p><label>{c.name}<input required name="full_name" autoComplete="name" /></label><label>{c.email}<input required name="email" type="email" autoComplete="email" /></label><label>{c.attendance}<select name="attendance" required value={attendance} onChange={(event) => { setAttendance(event.target.value); setReservedSeats(""); }}><option value="" disabled>—</option><option value="accept">{c.yes}</option><option value="decline">{c.no}</option></select></label>{attendance === "accept" && <label>{c.guests}<select name="reserved_seats" required value={reservedSeats} onChange={(event) => setReservedSeats(event.target.value)}><option value="" disabled>&mdash;</option><option value="all_seats">{c.allSeats}</option><option value="fewer_seats">{c.fewerSeats}</option></select><span className="normal-case tracking-normal text-xs leading-relaxed">{reservedSeats === "fewer_seats" ? c.fewerSeats : c.allSeats}</span></label>}{attendance === "accept" && reservedSeats === "fewer_seats" && <label>{c.guestCount}<input type="number" name="guest_count" required min="1" step="1" inputMode="numeric" /></label>}<label className="md:col-span-2">{c.message}<textarea name="message" rows={4} /></label>{submission === "error" && <p role="alert" className="md:col-span-2 text-sm text-[#a44d3c]">{c.retry}</p>}<button className="rsvp-submit md:col-span-2" disabled={submission === "sending"}>{submission === "sending" ? c.sending : c.submit}</button></form>}</div></section>
    <footer className="border-t border-[#cdbd9f] px-5 py-8 md:px-10"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 text-[10px] uppercase tracking-[0.2em] text-[#796a5c]"><span>© 2027 {siteTitle} · <a className="underline underline-offset-4 transition-opacity hover:opacity-60" href="https://www.instagram.com/sdigital.cr" target="_blank" rel="noreferrer">S-Digital</a></span><a className="footer-contact underline underline-offset-4" href="mailto:sterogam@gmail.com"><span>{c.project}</span><span className="normal-case tracking-normal">sterogam@gmail.com</span></a><button onClick={() => scrollTo("top")}>{c.back} ↑</button></div></footer>
  </main>;
}

export default App;
